export type OpcodeInstruction = {
    clearScreen: Function,
    draw: Function,
    jumpToAddress: Function,
    jumpToSubroutine: Function,
    jumpToAddressPlusRegister: Function,
    returnFromSubroutine: Function,
    skneXY: Function,
    skeqXY: Function,
    skneXKK: Function,
    skeqXKK: Function,
    skpr: Function,
    skup: Function,
    key: Function,
    or: Function,
    xor: Function,
    add: Function,
    and: Function,
    binaryCodedDecimal: Function,
    shiftLeft: Function,
    shiftRight: Function,
    subtract: Function,
    invertedSubtract: Function,
    setConstant: Function,
    addConstant: Function,
    setRegisterXWithY : Function,
    mvi: Function,
    ldr: Function,
    str: Function,
    adi: Function,
    font: Function,
    rand: Function,
    gDelay: Function,
    sDelay: Function,
    sSound: Function
}